name: Test install.sh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Run tests
      run: ./test/run-tests.sh

    - name: Check test results
      if: failure()
      run: echo "Tests failed. Check the output above for details."
